// Code generated by MockGen. DO NOT EDIT.
// Source: companyService.go
//
// Generated by this command:
//
//	mockgen -source=companyService.go -destination=companyservice_mock.go -package=servicesgo
//
// Package servicesgo is a generated GoMock package.
package services
