version: "3" 

services:
    job-portal-api:
      container_name: job-portal-api
      image: "jop-portal-api"
      ports:
        - "8086:8086"
      build: .
      env_file:
        - .env
        - .private.env
        - .public.env
        - .radies.env
      depends_on:
        - postgres
      restart: always
    postgres:
      container_name: postgres
      image: postgres
      ports:
        - "5432:5432"
      env_file:
        - .postgres.env
    redis:
      container_name: redis
      image: redis
      ports:
        - "6379:6379"
        


         
