// Code generated by MockGen. DO NOT EDIT.
// Source: jobDao.go
//
// Generated by this command:
//
//	mockgen -source=jobDao.go -destination=jobDao_mock.go -package=repository
//
// Package repository is a generated GoMock package.
package repository
